name: tourscan
description: A new Flutter project.

publish_to: 'none' # Remove this line if you plan to publish this package

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  modal_progress_hud_nsn: ^0.5.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  image_card: ^0.0.4
  camera: ^0.11.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  tflite_flutter: ^0.11.0
  image: ^4.0.17
  font_awesome_flutter: ^10.8.0
  flutter_localization: ^0.3.2
  flutter_tts: ^4.2.2
  flutter_svg: ^2.0.7
  http: ^1.3.0
  provider: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Google_Logo.svg
    - assets/
    - assets/profile/
    - assets/model/model.tflite
    - assets/model/labels.txt
    - assets/model/labels_ar.txt
flutter_intl:
  enabled: true
