name: tourscan
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  modal_progress_hud_nsn: ^0.5.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  image_card: ^0.0.4
  camera: ^0.11.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  tflite_flutter: ^0.11.0
  image: ^4.0.17  # لمعالجة الصور قبل إرسالها للنموذج
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/profile/
    - assets/model/model.tflite
    - assets/model/labels.txt
