// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtXKtjwfxAQsOlR9QDSwYTC0AbyC3Vars',
    appId: '1:279362613706:web:11c3bfb58cb6034d105f33',
    messagingSenderId: '279362613706',
    projectId: 'tour-scan',
    authDomain: 'tour-scan.firebaseapp.com',
    storageBucket: 'tour-scan.firebasestorage.app',
    measurementId: 'G-BW2GHXB9PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR67dMf9_W5GKOege2Xl8CtMAEQi-m6B4',
    appId: '1:279362613706:android:40aa2f16f7c3ca8c105f33',
    messagingSenderId: '279362613706',
    projectId: 'tour-scan',
    storageBucket: 'tour-scan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvQcfUi8hyKcO4nSLcwWKQuYVwV5W4Fns',
    appId: '1:279362613706:ios:1276f5d6fe2a86ac105f33',
    messagingSenderId: '279362613706',
    projectId: 'tour-scan',
    storageBucket: 'tour-scan.firebasestorage.app',
    iosClientId: '279362613706-0fpdmskcs6v3hbjvcogj4phuv7b4f0mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvQcfUi8hyKcO4nSLcwWKQuYVwV5W4Fns',
    appId: '1:279362613706:ios:1276f5d6fe2a86ac105f33',
    messagingSenderId: '279362613706',
    projectId: 'tour-scan',
    storageBucket: 'tour-scan.firebasestorage.app',
    iosClientId: '279362613706-0fpdmskcs6v3hbjvcogj4phuv7b4f0mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtXKtjwfxAQsOlR9QDSwYTC0AbyC3Vars',
    appId: '1:279362613706:web:89dfdf8378801af5105f33',
    messagingSenderId: '279362613706',
    projectId: 'tour-scan',
    authDomain: 'tour-scan.firebaseapp.com',
    storageBucket: 'tour-scan.firebasestorage.app',
    measurementId: 'G-2271R9FK50',
  );

}